// Centralized onboarding options used by both onboarding and profile edit

export const PURPOSE_OPTIONS = [
  { key: "list", label: "List myself as an expert vibecoder" },
  { key: "find", label: "Finds AI-first developers to work with" },
  { key: "get_hired", label: "Get hired" },
  { key: "hiring", label: "I'm hiring AI-first developers" },
];

export const VIBE_OPTIONS = [
  "Ship-first Vibecoder",
  "AI Agent Orchestrator",
  "Prompt Engineer",
  "Claude Code Wizard",
  "Cursor Power User",
  "Windsurf Navigator",
  "Model Fine-tuner",
  "RAG Architect",
  "Agentic Framework Builder",
  "LLM Whisperer",
  "Token Optimizer",
  "Reasoning Chain Designer",
];

export const STACK_CORE = [
  "Next.js",
  "TypeScript",
  "Python",
  "FastAPI",
  "React",
  "Vercel",
  "AWS",
  "Azure",
  "GCP",
  "Supabase",
  "Cloudflare",
  "Railway",
  "Netlify",
  "Render",
  "Mastra",
  "Agno",
  "SmolAgents",
  "CrewAI",
  "PydanticAI",
  "LangChain",
  "LangGraph",
  "AutoGen",
  // LLM Providers
  "OpenAI",
  "Anthropic",
  "Groq",
  "xAI Grok",
  "Gemini",
  "HuggingFace",
  "Replicate",
  "fal.ai",
  // AI Dev Tools
  "Cursor",
  "Windsurf",
  "Claude Code",
  "Codeium",
  // AI Builders
  "v0",
  "Lovable",
  "Bolt",
  // Video/Image AI
  "Runway",
  "Kling",
  "Wan",
  "Veo-3",
  "FLUX",
  "Imagen-4",
  // UI/Styling
  "TailwindCSS",
  "shadcn/ui",
  "Framer",
  // Database
  "PostgreSQL",
  "Drizzle",
  "Neon",
  "PostHog",
  "Postmark",
  "Stripe",
];

export const EXPERTISE_OTHER = [
  "Musician",
  "Artist",
  "Writer",
  "Photographer",
  "Videographer",
  "Designer",
  "Chef/Foodie",
  "Book Lover",
  "Gamer",
  "Athlete",
  "Traveler",
  "Language Learner",
  "Podcaster",
  "Content Creator",
  "Teacher",
  "Speaker",
  "Community Builder",
  "Consultant",
  "Entrepreneur",
  "Parent",
];
